# Generated by Django 6.0.6 on 2026-06-15 12:30

import accounts.managers
import accounts.models
import django.core.validators
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        # `citext` powers case-insensitive unique emails (TSD §3.3). Must exist
        # before the users table is created.
        CITextExtension(),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("email", accounts.models.CIEmailField(max_length=254, unique=True)),
                (
                    "phone",
                    models.CharField(
                        max_length=16,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone must be in E.164 format, e.g. +2348012345678.",
                                regex="^\\+[1-9]\\d{1,14}$",
                            )
                        ],
                    ),
                ),
                ("is_supplier", models.BooleanField(default=False)),
                ("is_hirer", models.BooleanField(default=False)),
                (
                    "account_level",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("verified", "Verified"),
                            ("business_verified", "Business verified"),
                        ],
                        default="basic",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("suspended_reason", models.TextField(blank=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", accounts.managers.UserManager()),
            ],
        ),
    ]
