# Generated by Django 6.0.6 on 2026-06-17 00:51

import core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpecTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset_class",
                    models.CharField(
                        choices=[
                            ("plant_machinery", "Plant & Machinery"),
                            ("trucks_haulage", "Trucks & Haulage"),
                            ("warehousing", "Warehousing & Storage"),
                            ("terminals_yards", "Terminals & Container Yards"),
                            ("land_staging", "Land & Staging"),
                        ],
                        max_length=32,
                    ),
                ),
                ("asset_type", models.CharField(max_length=100)),
                ("version", models.PositiveIntegerField(default=1)),
                ("fields", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "spec_templates",
                "indexes": [
                    models.Index(
                        fields=["asset_class", "asset_type"],
                        name="spec_templa_asset_c_ed0cd9_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("asset_class", "asset_type", "version"),
                        name="uniq_spec_template_class_type_version",
                    )
                ],
            },
        ),
    ]
