# Generated by Django 6.0.6 on 2026-06-17 00:56

import core.ids
import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_seed_spec_templates"),
        ("suppliers", "0002_yard"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset_class",
                    models.CharField(
                        choices=[
                            ("plant_machinery", "Plant & Machinery"),
                            ("trucks_haulage", "Trucks & Haulage"),
                            ("warehousing", "Warehousing & Storage"),
                            ("terminals_yards", "Terminals & Container Yards"),
                            ("land_staging", "Land & Staging"),
                        ],
                        max_length=32,
                    ),
                ),
                ("asset_type", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("specs", models.JSONField(default=dict)),
                ("spec_template_version", models.PositiveIntegerField(default=1)),
                ("daily_price", models.BigIntegerField()),
                ("weekly_price", models.BigIntegerField(blank=True, null=True)),
                ("monthly_price", models.BigIntegerField(blank=True, null=True)),
                ("unit_count", models.PositiveIntegerField(default=1)),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "address_text",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("city", models.CharField(blank=True, default="", max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("live", "Live"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                            ("removed", "Removed"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("verified", "Verified"),
                            ("inspected", "Inspected"),
                        ],
                        default="basic",
                        max_length=16,
                    ),
                ),
                ("report_count", models.PositiveIntegerField(default=0)),
                ("priority_review_flag", models.BooleanField(default=False)),
                ("completeness_score", models.FloatField(default=0.0)),
                ("removed_reason", models.TextField(blank=True, default="")),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "yard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to="suppliers.yard",
                    ),
                ),
            ],
            options={
                "db_table": "listings",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(blank=True, default="", max_length=120)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "db_table": "units",
            },
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["status", "asset_class"], name="listings_status_d084b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["supplier", "status"], name="listings_supplie_e375f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["specs"], name="listings_specs_gin"
            ),
        ),
    ]
