# Generated by Django 6.0.6 on 2026-06-17 01:01

import core.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_listing_unit_listing_listings_status_d084b7_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("r2_key", models.CharField(max_length=255)),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_cover", models.BooleanField(default=False)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "db_table": "listing_photos",
                "ordering": ["position"],
            },
        ),
    ]
