# Generated by Django 6.0.6 on 2026-06-17 01:06

import core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_listingphoto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("fraudulent", "Fraudulent"),
                            ("inaccurate", "Inaccurate"),
                            ("inappropriate", "Inappropriate"),
                            ("duplicate", "Duplicate"),
                            ("unavailable", "Unavailable"),
                        ],
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("dismissed", "Dismissed"),
                            ("warned", "Warned"),
                            ("removed", "Removed"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("resolution_note", models.TextField(blank=True, default="")),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="listings.listing",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filed_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reports",
                "indexes": [
                    models.Index(
                        fields=["listing", "created_at"],
                        name="reports_listing_d249ab_idx",
                    )
                ],
            },
        ),
    ]
