# Generated by Django 5.2.14 on 2026-05-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='commission_rate_label',
            field=models.CharField(default='10%', help_text='Human-readable rate applied, e.g. "12%", "₦2,500 flat"', max_length=30),
        ),
    ]
