# Generated by Django 5.2.14 on 2026-05-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_tiered_commission_rate_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('cancelled_renter', 'Cancelled by Renter'), ('cancelled_owner', 'Cancelled by Owner'), ('cancelled_admin', 'Cancelled by Admin')], default='pending', max_length=20),
        ),
    ]
