# Generated by Django 6.0.6 on 2026-06-17 00:32

import core.fields
import core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("logo_key", models.CharField(blank=True, default="", max_length=255)),
                ("bank_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "bank_account_number_enc",
                    core.fields.EncryptedTextField(blank=True, default=""),
                ),
                (
                    "bank_account_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("notif_hire_requests", models.BooleanField(default=True)),
                ("notif_messages", models.BooleanField(default=True)),
                ("notif_payouts", models.BooleanField(default=True)),
                ("notif_marketing", models.BooleanField(default=True)),
                ("strike_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "supplier_profiles",
            },
        ),
    ]
